### ISSUE TITLE
Mirrors - policy adding mirrors - check broken mirrors

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/lunar#115]
Do you have a policy for adding mirrors to the existing list of mirrors in lunar? I mean, I assume mirrors would like to have there permission to add them to lunar's list of mirrors?
I noticed broken mirrors. And maybe I can help with that?

have a great day!

**Comment by bsfc1685** [comment]
yeah, like an /etc/lunar/mirrors/module.override for locally persistent URLs, per-module... Which would be used by lget via /var/lib/lunar/plugins/download*? It would be handy, I used to modify the module's DETAILS for URL readjust, although rarely
