### ISSUE TITLE
mark renames

### ISSUE THREAD

**Issue by v4hn** [lunar-linux/lunar#128]
We should have a way to notify the system if the name of a module changed.

I would propose to have a simple file `RENAMES` in the moonbase(s) that consists of lines like
```
tbb -> intel-tbb
```
At the moment the update system notices that a module is gone and encourages the user to remove it from the system. Instead it can go through the file and propose to remove the old and install the new module.

If the file ever gets too big, we could just drop old entries.

This shouldn't be a hassle to implement and would remove some frustration with looking up new package names.

**Comment by Ratler** [comment]
Functionality to replace a module by using REPLACES= in DETAILS for the new module has been added. Closing.
