### ISSUE TITLE
BUG: When installing a module with dependencies, only the first dependency is installed

### ISSUE THREAD

**Issue by dagbrown** [lunar-linux/lunar#139]
When installing a module with any number of dependencies, `lin module` installs only the first dependency and then returns to the command line.

To reproduce:

    # lin darktable

It installed the first dependency that isn't already installed--in my case, exiv2--and then lin just exited and dropped me back to the command-line prompt.

The problem was first reported by tbeckerson and confirmed by me.

**Comment by tbeckerson** [comment]
A bit more detail:

Each time you invoke _lin,_ it will install exactly one program, then exit. So for something like _darktable,_ you'd need to enter _lin darktable_ about 20 times.

If you try to install multiple modules, _lin darktable inkscape,_ it installs two programs - the first dependency of each - then quits.
