### ISSUE TITLE
lunar: lunar update syntax error

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/lunar#161]
bash-5.0# lunar update
Downloading source file moonbase.tar.bz2 for module moonbase
--2020-11-06 21:35:01--  http://lunar-linux.org/lunar//moonbase.tar.bz2
Resolving lunar-linux.org (lunar-linux.org)... 2a03:b0c0:0:1010::5d:b001, 188.226.242.178
Connecting to lunar-linux.org (lunar-linux.org)|2a03:b0c0:0:1010::5d:b001|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1945933 (1.9M) [application/x-bzip2]
Saving to: '/tmp/moonbase.tar.bz2'

/tmp/moonbase.tar.b 100%[===================>]   1.86M  4.61KB/s    in 6m 42s  

2020-11-06 21:41:44 (4.73 KB/s) - '/tmp/moonbase.tar.bz2' saved [1945933/1945933]

Preparing to install moonbase.tar.bz2 ...
Removed module: moonbase
Extracting moonbase.tar.bz2 ...
Created /var/log/lunar/install/moonbase-20201106.13 
Creating /var/log/lunar/md5sum/moonbase-20201106.13
Starting update of installed modules
/var/lib/lunar/functions/modules.lunar: line 714: ((: > 20201024 : syntax error: operand expected (error token is "> 20201024 ")

**Comment by Ratler** [comment]
Can't reproduce. But judging by where in the code this error occurred, it must have been a module with a broken UPDATED field, most likely already fixed.
