### ISSUE TITLE
'lvu depends' takes very long to execute

### ISSUE THREAD

**Issue by esselfe** [lunar-linux/lunar#162]
Running e.g. 'lvu depends openssl' takes over 10 hours. stumbles even reported over 24 hours. Maybe something like:  
```
for m in $@; do
	find /var/lib/lunar/moonbase -name DEPENDS -exec grep -H "depends.*$m " '{}' \;
done
```
Output:
```
[...]  
/var/lib/lunar/moonbase/other/ftp/vsftpd/DEPENDS:optional_depends openssl   "" "" "for SSL support"  
/var/lib/lunar/moonbase/other/ftp/pure-ftpd/DEPENDS:optional_depends openssl   "--with-tls" "" "for SSL/TLS support"  
/var/lib/lunar/moonbase/other/devel/opensc/DEPENDS:optional_depends %OSSL "--enable-openssl" "--disable-openssl" "for openssl support"  
/var/lib/lunar/moonbase/other/libs/PDFlib-Lite/DEPENDS:optional_depends "openssl"   ""                                      "--without-openssl" "for openssl support"  
[...]
```
This one takes 31 seconds without disk cache (dropped) and 15s with.  Of course the output should be worked upon, like:
- strip /var/lib/lunar/moonbase/  
- strip configuration flags  
- strip the description text  
- write (on|off|unset)

**Comment by v4hn** [comment]
Yes, `openssl/POST_INSTALL` takes forever for no obvious reason.
Beware, `lvu depends` includes recursive dependencies as well though.

**Comment by dagbrown** [comment]
I've submitted a [PR](https://github.com/lunar-linux/lunar/pull/166) to address this.

**Comment by esselfe** [comment]
Fixed in https://github.com/lunar-linux/lunar/pull/166
