### ISSUE TITLE
modules.lunar:some warning

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/lunar#164]
Starting update of installed modules
vte was removed from /var/lib/lunar/moonbase
vte: Do you want to remove vte ? [y] 
Removed module: vte
/var/lib/lunar/functions/modules.lunar: line 690: continue: only meaningful in a `for', `while', or `until' loop
fftw3 was removed from /var/lib/lunar/moonbase
fftw3: Do you want to remove fftw3 ? [y] 
Removed module: fftw3
/var/lib/lunar/functions/modules.lunar: line 690: continue: only meaningful in a `for', `while', or `until' loop

**Comment by Ratler** [comment]
Fixed in https://github.com/lunar-linux/lunar/commit/8da37b0b316ccf31a0fe9414bfd960d9bae9fd61

Pending release of version 41.
