### ISSUE TITLE
'lin -r' doesn't reprompt optional features from DEPENDS.

### ISSUE THREAD

**Issue by esselfe** [lunar-linux/lunar#182]
Recently I noticed that 'lin -r module_name_here' doesn't always prompt the user for a module's deps. For example when I run 'lin -r btrfs-progs' it doesn't ask whether to enable asciidoc/xmlto or not. I had to edit /var/state/lunar/depends{,.cache,.backup} manually.

Note that's it sometimes works, sometimes half way, sometimes not at all.

I gave a look at the code but I see nothing.

**Comment by esselfe** [comment]
And 'lunar set LUNAR_DEBUG 1' doesn't say much...

**Comment by Ratler** [comment]
@esselfe it is expected behavior if arg2 and arg3 are left empty e.g. "" and the module is installed on the system, it will be automatically added as a dependency.
